### ISSUE TITLE
Compatibility with jekyll 3.2.1

### ISSUE THREAD

**Issue by ghost** [mattgemmell/Jekyll-Multipage#2]
I get the following Error when I try to use this plugin:
`Deprecation: Document#title is now a key in the #data hash.
       Deprecation: Called by /home/jekyll/_plugins/multipage-generator.rb:65:in`create_multipage'.
`

**Comment by vallieres** [comment]
Same problems here...

```
      Deprecation: posts.find_all should be changed toposts.docs.find_all.
                    Called by /_plugins/multipage-generator.rb:670:in `process_multipages'.
       Deprecation: Document#title is now a key in the #data hash.
       Deprecation: Called by /_plugins/multipage-generator.rb:65:in `create_multipage'.
/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.1/lib/jekyll/document.rb:370:in `method_missing': undefined method `name' for #<Jekyll::Document:0x007fe1f42c7f08> (NoMethodError)
	from /_plugins/multipage-generator.rb:68:in `create_multipage'
```

@hnaseri89 any luck luck on your side?
